<?xml version="1.0"?>
<robot name="simple_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Robot namespace -->
  <xacro:arg name="robot_name" default="robot"/>

  <!-- Constants -->
  <xacro:property name="base_radius" value="0.15"/>
  <xacro:property name="base_height" value="0.1"/>
  <xacro:property name="wheel_radius" value="0.05"/>
  <xacro:property name="wheel_width" value="0.04"/>
  <xacro:property name="wheel_separation" value="0.3"/>

  <!-- ================= BASE ================= -->

  <link name="base_footprint"/>

  <link name="base_link">
    <visual>
      <geometry>
        <cylinder radius="${base_radius}" length="${base_height}"/>
      </geometry>
      <material name="blue">
        <color rgba="0 0 0.8 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${base_radius}" length="${base_height}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="5.0"/>
      <inertia ixx="0.01" ixy="0.0" ixz="0.0"
               iyy="0.01" iyz="0.0"
               izz="0.01"/>
    </inertial>
  </link>

  <joint name="base_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0 0 0.05" rpy="0 0 0"/>
  </joint>

  <!-- ================= LIDAR (FIXED) ================= -->

  <!-- IMPORTANT:
       Link name is now "lidar" (not lidar_link)
       This MUST match the LaserScan frame_id
  -->

  <link name="lidar">
    <visual>
      <geometry>
        <cylinder radius="0.05" length="0.04"/>
      </geometry>
      <material name="black">
        <color rgba="0 0 0 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="0.05" length="0.04"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.1"/>
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
               iyy="0.0001" iyz="0.0"
               izz="0.0001"/>
    </inertial>
  </link>

  <joint name="lidar_joint" type="fixed">
    <parent link="base_link"/>
    <child link="lidar"/>
    <origin xyz="0 0 0.08" rpy="0 0 0"/>
  </joint>

  <!-- ================= GAZEBO LIDAR ================= -->

  <gazebo reference="lidar">
    <sensor name="lidar" type="gpu_lidar">
      <pose>0 0 0 0 0 0</pose>
      <frame_name>$(arg robot_name)/lidar</frame_name>
      <topic>$(arg robot_name)/scan</topic>
      <update_rate>10</update_rate>

      <lidar>
        <scan>
          <horizontal>
            <samples>360</samples>
            <resolution>1.0</resolution>
            <min_angle>-3.14159</min_angle>
            <max_angle>3.14159</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.12</min>
          <max>10.0</max>
          <resolution>0.01</resolution>
        </range>
      </lidar>

      <always_on>true</always_on>
      <visualize>true</visualize>
    </sensor>
  </gazebo>

  <!-- ================= DIFF DRIVE (MULTI-ROBOT SAFE) ================= -->

  <gazebo>
    <plugin filename="gz-sim-diff-drive-system"
            name="gz::sim::systems::DiffDrive">

      <left_joint>left_wheel_joint</left_joint>
      <right_joint>right_wheel_joint</right_joint>

      <wheel_separation>${wheel_separation}</wheel_separation>
      <wheel_radius>${wheel_radius}</wheel_radius>

      <topic>$(arg robot_name)/cmd_vel</topic>
      <odom_topic>$(arg robot_name)/odom</odom_topic>

      <!-- CRITICAL FIX -->
      <odom_frame>$(arg robot_name)/odom</odom_frame>
      <child_frame_id>$(arg robot_name)/base_footprint</child_frame_id>

      <publish_odom>true</publish_odom>
      <publish_odom_tf>true</publish_odom_tf>
      <use_sim_time>true</use_sim_time>

      <publish_wheel_tf>false</publish_wheel_tf>
      <odom_publish_frequency>50</odom_publish_frequency>
    </plugin>
  </gazebo>

  <!-- ================= POSE PUBLISHER ================= -->

  <gazebo>
    <plugin filename="gz-sim-pose-publisher-system"
            name="gz::sim::systems::PosePublisher">
      <topic>$(arg robot_name)/tf</topic>
    </plugin>
  </gazebo>


  <gazebo>
    <plugin filename="gz-sim-odometry-publisher-system"
            name="gz::sim::systems::OdometryPublisher">
      <odom_topic>$(arg robot_name)/odom</odom_topic>
      <odom_frame>$(arg robot_name)/odom</odom_frame>
      <robot_base_frame>$(arg robot_name)/base_footprint</robot_base_frame>
      <odom_publish_frequency>50</odom_publish_frequency>
    </plugin>
  </gazebo>


  <!-- ================= WHEELS ================= -->

  <link name="left_wheel">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="1.5708 0 0"/>
      <material name="gray">
        <color rgba="0.5 0.5 0.5 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="1.5708 0 0"/>
    </collision>
    <inertial>
      <mass value="0.5"/>
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
               iyy="0.0001" iyz="0.0"
               izz="0.0001"/>
    </inertial>
  </link>

  <joint name="left_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="left_wheel"/>
    <origin xyz="0 ${wheel_separation/2} -0.03" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <link name="right_wheel">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="1.5708 0 0"/>
      <material name="gray">
        <color rgba="0.5 0.5 0.5 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="1.5708 0 0"/>
    </collision>
    <inertial>
      <mass value="0.5"/>
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
               iyy="0.0001" iyz="0.0"
               izz="0.0001"/>
    </inertial>
  </link>

  <joint name="right_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="right_wheel"/>
    <origin xyz="0 ${-wheel_separation/2} -0.03" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

</robot>
