services:
  ros2_dev:
    build: .
    container_name: multi_robot_slam
    network_mode: host
    privileged: true
    stdin_open: true
    tty: true
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=${XAUTHORITY}
      - ROS_DOMAIN_ID=0
    volumes:
      - ./src:/ros2_ws/src
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${XAUTHORITY}:/root/.Xauthority
      - ros2_build:/ros2_ws/build
      - ros2_install:/ros2_ws/install
    devices:
      - /dev/dri:/dev/dri

volumes:
  ros2_build:
  ros2_install: